[project]
name = "04-slack-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "load-dotenv>=0.1.0",
    "slack-sdk>=3.36.0",
    "boto3>=1.34.0",
    "jsbeautifier>=1.15.4",
]
